name: 天气推送

on:
  schedule:
    # 北京时间早上8点 = UTC时间0点
    - cron: '00 0 * * *'  # UTC时间0点（北京时间8点）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区环境变量
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"

      - name: Install dependencies
        run: uv sync

      - name: Run weather Report
        run: uv run main.py
        env:
          TZ: Asia/Shanghai
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          OPEN_ID: ${{ secrets.OPEN_ID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          LOCATION: ${{ secrets.LOCATION }}