name: 天气推送

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早7点
    - cron: '00 23 * * *'  # 修正了时间，UTC23点对应北京时间第二天7点
  # 添加一个手动触发器
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 这个action可以获取到仓库文件
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"

      - name: Install dependencies
        run: uv sync

      - name: Run weather Report
        run: uv run main.py
        env:  # 关键修复：在这里设置环境变量
          TZ: Asia/Shanghai
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          OPEN_ID: ${{ secrets.OPEN_ID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}